### ISSUE TITLE
Island Mode - Island failing to locate

### ISSUE THREAD

**Issue by arts7493** [endercrest/VoidSpawn#65]
**Describe the bug**
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island
[23:28:10] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[23:28:10] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island

**To Reproduce**

**Expected behavior**
i set island mode with bentobox
but cant warp and error

**Screenshots**

**VoidSpawn Version:** 1.18.3
**MC Version:** 1.15.2
**Spigot Version:** paper-208

**Additional context**

**Comment by endercrest** [comment]
Hey, thanks for opening this. Could you provide your `worlds.yml` here so I can better understand your configuration setup?

**Comment by endercrest** [comment]
I have also looked into using a different API provided by BentoBox, but there is a bug in their system. I have just opened a ticket to get that resolved. https://github.com/BentoBoxWorld/BentoBox/issues/1306. Once that gets resolved, I will look into improving this logic.

**Comment by endercrest** [comment]
Closing this off as a fix is available. Also, you should set a fallback spawn (`/vs set`)

**Comment by arts7493** [comment]
still can't
[17:44:04] [Server thread/INFO]: [VoidSpawn] Error while teleporting player: No island found
[17:44:04] [Server thread/INFO]: [VoidSpawn] Details, World: bskyblock_world, Mode: Island

**Comment by endercrest** [comment]
@arts7493 Is it possible that the player doesn't have an island? Also, it is recommended setting a fallback spawn point in case the player doesn't have an island.

**Comment by arts7493** [comment]
already have island
but always warp to spawn
spawn point = server spawn
